spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

jpa:
  hibernate:
    ddl-auto: validate

server:
  port: ${PORT:8080}

apiKey: ${API_KEY}