name: Keep Supabase Alive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'  # ping every 3 days at 00:00 UTC

jobs:
  ping: #define a job called ping
    runs-on: ubuntu-latest
    steps:
      - name: Ping Spring Boot health endpoint to touch DB
        run: curl -I https://poetry-api-1.onrender.com/api/v1/poem/health